import './globals.css'
import Header from './_components/header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <Header />

        <div>{children}</div>
      </body>
    </html>
  )
}
